"""
Django settings for survey_hos project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-26i@b_mr+%m+d61w15ydx1gmkv1$317xi0w9q9l%^7h-p1p@(_'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    "django_browser_reload",
    'survey',
    'manager',
    'modeltranslation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'survey_hos.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'manager', 'templates'), # <--- ใส่บรรทัดนี้เพิ่มเข้าไปครับ!
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'survey.context_processors.notifications',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_hos.wsgi.application'

REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'survey',                  
        'USER': 'survey',                 
        'PASSWORD': 'Tk10951!',  
        'HOST': '192.168.63.17',           
        'PORT': '3306',                 
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th-th'

TIME_ZONE = 'Asia/Bangkok' # เขตเวลาไทย

USE_I18N = True
USE_L10N = True
USE_TZ = True # สำคัญ: ต้องเปิดไว้เพื่อให้ Django จัดการ Timezone ได้ถูกต้อง


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]   

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'       # เช่น 'smtp.gmail.com' หรือ 'smtp.office365.com'
EMAIL_PORT = 587                    # พอร์ตมาตรฐาน
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wuttinan.lu.65@ubu.ac.th' # อีเมลที่ใช้ส่ง
EMAIL_HOST_PASSWORD = 'sbcl rcae gbyt wdsn' # รหัสผ่านหรือ App Password
DEFAULT_FROM_EMAIL = 'Survey Hospital Alert <your_alert_email@hospital.com>'


LINE_CHANNEL_ACCESS_TOKEN = 'Q9qgDx82kKnRm48G/wTVmrFIKoDrIaN3d/0f0aEsl2LyrcDZoU3x4jWuShgI2/jtTe3Vd5bNJmIicgoyASeOQIkioOvoTcu3/p2wYlj3+n5jFlWVRUvOjjXUwjwJBF9dsblrr0171+3ZevUb9pZnUQdB04t89/1O/w1cDnyilFU='
LINE_ADMIN_RECIPIENT_ID = 'U1139a44d8fde0b4ef010f6f70f136eb2'
FULL_DOMAIN = "http://127.0.0.1:8000"

# กำหนดอายุของ Session เป็นวินาที (8 ชั่วโมง)
# 8 ชม. x 60 นาที x 60 วินาที = 28,800 วินาที
SESSION_COOKIE_AGE = 8 * 60 * 60
# (Optional 2) ครบ 8 ชม. จากตอนล็อกอิน ตัดทันที (แม้จะกำลังทำงานอยู่)
SESSION_SAVE_EVERY_REQUEST = True

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('th', _('Thai')),
    ('en', _('English')),
]

# โฟลเดอร์สำหรับเก็บไฟล์แปล (Optional: ถ้าจะแปลข้อความ Static)
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Modeltranslation Settings
MODELTRANSLATION_DEFAULT_LANGUAGE = 'th'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('th', 'en')

