# Generated by Django 5.2.7 on 2025-11-10 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('hn_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='HN (Hashed)')),
                ('pdpa_accepted', models.BooleanField(default=False, verbose_name='ยอมรับ PDPA')),
                ('patient_type', models.CharField(blank=True, choices=[('NEW', 'ผู้ป่วยใหม่'), ('EXISTING', 'ผู้ป่วยเก่า (นัดหมาย)')], max_length=20, null=True, verbose_name='ประเภทผู้ป่วย')),
                ('user_role', models.CharField(blank=True, choices=[('PATIENT', 'ผู้ป่วย'), ('RELATIVE', 'ญาติ')], max_length=20, null=True, verbose_name='ผู้ตอบ')),
                ('benefit_plan', models.CharField(blank=True, choices=[('UC', 'สิทธิบัตรทอง'), ('SOCIAL_SECURITY', 'ประกันสังคม'), ('GOVERNMENT', 'สิทธิข้าราชการ/เบิกจ่ายตรง'), ('SELF_PAY', 'ชำระเงินเอง (เงินสด)'), ('OTHER', 'อื่น ๆ')], max_length=30, null=True, verbose_name='สิทธิการรักษา')),
                ('benefit_plan_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='สิทธิอื่น ๆ')),
                ('age_range', models.CharField(blank=True, choices=[('UNDER_15', 'ต่ำกว่า 15 ปี'), ('15_25', '15-25 ปี'), ('26_40', '26-40 ปี'), ('41_60', '41-60 ปี'), ('OVER_60', 'มากกว่า 60 ปี')], max_length=20, null=True, verbose_name='ช่วงอายุ')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'ชาย'), ('FEMALE', 'หญิง'), ('OTHER', 'อื่น ๆ'), ('NOT_SPECIFIED', 'ไม่ระบุ')], max_length=20, null=True, verbose_name='เพศ')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาเริ่มตอบ')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลากดส่ง')),
            ],
            options={
                'verbose_name': 'การตอบกลับ (Response)',
                'verbose_name_plural': 'การตอบกลับ (Responses)',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='การกระทำ')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตาราง')),
                ('record_id', models.BigIntegerField(blank=True, null=True, verbose_name='Record ID')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='รายละเอียด (ก่อน/หลัง)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้กระทำ')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('RATING_5', 'คะแนน 1-5 ดาว'), ('YES_NO', 'ใช่ / ไม่ใช่'), ('TEXTAREA', 'ข้อความ (หลายบรรทัด)'), ('TEXT_SHORT', 'ข้อความ (บรรทัดเดียว)'), ('MULTIPLE_CHOICE', 'หลายตัวเลือก (เลือก 1)'), ('CHECKBOXES', 'หลายตัวเลือก (เลือกหลายอัน)')], max_length=20, verbose_name='ประเภทคำถาม')),
                ('text_th', models.TextField(verbose_name='ข้อความคำถาม (TH)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='ข้อความคำถาม (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('is_required', models.BooleanField(default=False, verbose_name='บังคับตอบ')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': '4. คำถาม (Question)',
                'verbose_name_plural': '4. คำถาม (Question)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อกฎแจ้งเตือน')),
                ('condition_type', models.CharField(choices=[('EQUALS', 'เท่ากับ'), ('NOT_EQUALS', 'ไม่เท่ากับ'), ('LESS_THAN', 'น้อยกว่า'), ('GREATER_THAN', 'มากกว่า'), ('CONTAINS', 'มีคำว่า')], max_length=20, verbose_name='เงื่อนไข')),
                ('condition_value', models.CharField(max_length=255, verbose_name='ค่าที่ตรวจสอบ (เช่น 6 หรือ ID ตัวเลือก)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='คำถามที่ตรวจสอบ')),
            ],
            options={
                'verbose_name': 'กฎการแจ้งเตือน',
                'verbose_name_plural': 'กฎการแจ้งเตือน',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_th', models.CharField(max_length=255, verbose_name='ข้อความตัวเลือก (TH)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ข้อความตัวเลือก (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='ค่าที่เก็บจริง (ถ้ามี)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question')),
            ],
            options={
                'verbose_name': '5. ตัวเลือก (Option)',
                'verbose_name_plural': '5. ตัวเลือก (Option)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'ใหม่'), ('ACKNOWLEDGED', 'รับทราบแล้ว'), ('RESOLVED', 'แก้ไขแล้ว')], default='NEW', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาเกิด')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาแก้ไข')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.alertrule', verbose_name='กฎที่ตรง')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.response', verbose_name='การตอบกลับ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน (Alert)',
                'verbose_name_plural': 'การแจ้งเตือน (Alerts)',
            },
        ),
        migrations.CreateModel(
            name='ResponseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, null=True, verbose_name='ค่าที่ตอบ (Text, NPS, Rating)')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.questionoption', verbose_name='ตัวเลือกที่ตอบ')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question', verbose_name='คำถาม')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.response', verbose_name='การตอบกลับ')),
            ],
            options={
                'verbose_name': 'คำตอบย่อย',
                'verbose_name_plural': 'คำตอบย่อย',
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="เช่น 'จุดเจาะเลือด Lab 1'", max_length=255)),
                ('code', models.CharField(help_text="รหัส Kiosk เช่น 'LAB-01'", max_length=50, unique=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Manager ที่รับผิดชอบจุดบริการนี้', related_name='managed_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='service_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.servicepoint', verbose_name='จุดบริการ'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=255, verbose_name='ชื่อแบบสอบถาม (TH)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อแบบสอบถาม (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': '1. แบบสอบถาม (Survey)',
                'verbose_name_plural': '1. แบบสอบถาม (Survey)',
            },
        ),
        migrations.CreateModel(
            name='SurveyServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.servicepoint')),
            ],
            options={
                'verbose_name': 'การกำหนดจุดบริการ',
                'verbose_name_plural': 'การกำหนดจุดบริการ',
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, verbose_name='ชื่อ/เลข เวอร์ชัน')),
                ('status', models.CharField(choices=[('DRAFT', 'ฉบับร่าง'), ('ACTIVE', 'ใช้งาน'), ('ARCHIVED', 'เก็บถาวร')], default='DRAFT', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_versions', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('service_points', models.ManyToManyField(related_name='survey_versions', through='survey.SurveyServicePoint', to='survey.servicepoint', verbose_name='จุดบริการที่ใช้งาน')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='surveyservicepoint',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyversion'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.surveyversion', verbose_name='เวอร์ชันแบบสอบถาม'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.surveyversion', verbose_name='เวอร์ชันของแบบสอบถาม'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyversion', verbose_name='เวอร์ชันแบบสอบถาม'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyservicepoint',
            unique_together={('survey_version', 'service_point')},
        ),
    ]
