# Generated by Django 5.2.7 on 2025-11-04 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="เช่น 'จุดเจาะเลือด Lab 1'", max_length=255)),
                ('code', models.CharField(help_text="รหัส Kiosk เช่น 'LAB-01'", max_length=50, unique=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Manager ที่รับผิดชอบจุดบริการนี้', related_name='managed_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
