# Generated by Django 5.2.8 on 2025-11-12 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='code',
            field=models.CharField(help_text='รหัส Code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Manager (User) ที่รับผิดชอบจุดบริการนี้', related_name='managed_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='name',
            field=models.CharField(help_text='ชื่อจุดบริการ', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='group',
            field=models.ForeignKey(blank=True, help_text='จุดบริการนี้ อยู่ในกลุ่มภารกิจใด', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_points', to='survey.servicegroup'),
        ),
    ]
