# Generated by Django 5.2.8 on 2025-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': '1. แบบสอบถาม (Survey)'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='version_number',
            field=models.CharField(default='1.0', max_length=50, verbose_name='เลขเวอร์ชัน'),
        ),
    ]
