# Generated by Django 5.2.8 on 2025-11-13 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_servicegroup_alter_servicepoint_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyversion',
            options={'ordering': ['-created_at'], 'verbose_name': '2. เวอร์ชันแบบสอบถาม', 'verbose_name_plural': '2. เวอร์ชันแบบสอบถาม'},
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบาย'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='บังคับตอบ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RATING_5', 'คะแนน 1-5 ดาว'), ('YES_NO', 'ใช่ / ไม่ใช่'), ('TEXTAREA', 'ข้อความ (หลายบรรทัด)'), ('TEXT_SHORT', 'ข้อความ (บรรทัดเดียว)'), ('MULTIPLE_CHOICE', 'หลายตัวเลือก (เลือก 1)'), ('CHECKBOXES', 'หลายตัวเลือก (เลือกหลายอัน)')], default='RATING_5', max_length=20, verbose_name='ประเภทคำถาม'),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='answer_value',
            field=models.TextField(blank=True, null=True, verbose_name='คำตอบ (Text/Value)'),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.questionoption'),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question'),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.response'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ฉบับร่าง'), ('ACTIVE', 'ใช้งานจริง'), ('ARCHIVED', 'เก็บถาวร')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='version_number',
            field=models.CharField(max_length=50, verbose_name='เลขเวอร์ชัน (เช่น 1.0)'),
        ),
    ]
