# Generated by Django 5.2.7 on 2025-11-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_section_alertrule_auditlog_questionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RATING_5', 'คะแนน 1-5 ดาว (Rating)'), ('TEXTAREA', 'ตอบยาว (Textarea)')], max_length=20, verbose_name='ประเภทคำถาม'),
        ),
    ]
