# Generated by Django 5.2.8 on 2025-11-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_options_alter_survey_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='survey_version',
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.survey', verbose_name='แบบสอบถาม'),
            preserve_default=False,
        ),
    ]
